language: python

python:
    - "3.7"
env:
    - SECRET_KEY='TEST'
services:
    - postgresql
install:
    - pip install -r requirements.txt
scripts:
    - coverage run --source='authentication' manage.py test && coverage report
after_success:
    - codecov
